name: Build and Release
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: mpickering
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build site.nix
    - name: Deploy to GitHub Pages
      uses: mpickering/github-pages-deploy-action@dev
      with:
        BRANCH: test-docs
        FOLDER: result
        REPOSITORY_NAME: mpickering/mpickering.github.io
        ACCESS_TOKEN: ${{ secrets.GH_SECRET }}


